pub const Id = enum(u16) {
    root = 1,
    home,
    contacts,
    chat,
    composer,
    ehagaki,
    header,
    title,
    line,
    home_contacts,
    home_ehagaki,
    contact_border,
    contact_label,
    qsp_label,
    cq_label,
    tuner,
    knob,
    chat_viewport,
    chat_content,
    chat_scrollbar,
    chat_separator,
    chat_hint,
    body,
    morse,
    decoded,
    footer_line,
    footer_hint,
    canvas_bitmap,
    canvas_border,
    cursor,
    tool_preview,
    toolbar_panel,
    toolbar_title,
    toolbar_hint,
    _,
};

pub fn message(index: usize, part: u1) Id {
    return @fromBackingInt(@intCast(200 + index * 2 + part));
}
