#!/usr/bin/env python3
"""Inventory pinned source without using a dirty reference checkout."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import re
import subprocess
import tarfile
import tempfile
from capture_mobus_reference import COMMIT, function


def calls(source):
    # Keep source expressions, not guessed/evaluated dynamic coordinates.
    lines=[]
    for m in re.finditer(r"(?:sprite|lcd)\.(?:draw\w*|fill\w*|setFont|setCursor|setText\w*|print|push\w*|clearClipRect)\s*\(",source):
        end=m.end();depth=1
        while end<len(source) and depth:
            depth+=(source[end]=="(")-(source[end]==")");end+=1
        lines.append(" ".join(source[m.start():end].split()))
    return lines


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo",type=Path,required=True)
    p.add_argument("--output",type=Path,required=True)
    a=p.parse_args()
    with tempfile.TemporaryDirectory(prefix="mimoc-inventory-") as temp:
        root=Path(temp)
        with tarfile.open(fileobj=io.BytesIO(subprocess.check_output(["git","-C",str(a.repo),"archive",COMMIT]))) as tar:
            tar.extractall(root,filter="data")
        paths=sorted(set(root.glob("main/runtime/**/*.[ch]pp"))|set(root.glob("components/display/**/*.[ch]pp"))|set(root.glob("components/ui/**/*.[ch]pp")))
        texts={str(p.relative_to(root)):p.read_text() for p in paths}
        facade=texts["main/runtime/display_facade.cpp"]
        entries=[]
        for match in re.finditer(r"^(?:void|int|WatchScreenResult) ((?:render_|show_watch|display_render_ota)[A-Za-z0-9_]*)\s*\(",facade,re.M):
            name=match[1];body=function(facade,match[0].strip())
            first=facade[:match.start()].count("\n")+1
            sites=[]
            for file,text in texts.items():
                if file=="main/runtime/display_facade.cpp" or file.endswith("display_facade.hpp"):continue
                for site in re.finditer(r"\b"+re.escape(name)+r"\s*\(",text):
                    sites.append({"file":file,"line":text[:site.start()].count("\n")+1})
            entries.append({"name":name,"source":"main/runtime/display_facade.cpp","line":first,"signature":" ".join(body[:body.index("{")].split()),"callers":sites,"constants":[line.strip() for line in body.splitlines() if re.search(r"(?:constexpr|static constexpr|const int|const bool|const uint)",line)],"drawing":calls(body),"delegates":sorted(set(re.findall(r"(?:display::renderer::|mvp_oled\(\)\.)([A-Za-z0-9_]+)",body))),"dynamic_tokens":sorted(set(re.findall(r"\b(?:now_us|started_us|percent|elapsed_s|cursor_on|playing|playhead|flip_inset|blink|offset_y|text_scroll_line|language_overlay_until_us|text_reveal_elapsed_us)\b",body)))})
        renderer_files={file:{"sha256":hashlib.sha256(text.encode()).hexdigest(),"drawing":calls(text),"constants":[l.strip() for l in text.splitlines() if "constexpr" in l or "const int" in l]} for file,text in texts.items() if "/renderer/" in file or file.endswith("legacy/screens/oled_view.hpp") or file.endswith("legacy/runtime/prelude.hpp")}
        result={"commit":COMMIT,"units":"logical pixels,128x64","facade":entries,"renderer_files":renderer_files,"screen_files":[f for f in texts if "main/runtime/screens/" in f],"ui_model_files":[f for f in texts if "components/ui/" in f],"all_source_sha256":{file:hashlib.sha256(text.encode()).hexdigest() for file,text in texts.items()}}
        a.output.mkdir(parents=True,exist_ok=True)
        (a.output/"mobus-source-inventory.json").write_text(json.dumps(result,indent=2,ensure_ascii=False)+"\n")
        md=["# Pinned renderer coordinate inventory", "", "Generated by `tools/mobus_reference_inventory.py`; commit `"+COMMIT+"`.", "", "These are original source expressions. Dynamic expressions are intentionally not converted to guessed pixel values. See `mobus-pixel-reference.md` for scenario coverage and interpretation.", ""]
        for e in entries:
            md += ["## "+e["name"],"",f"Source: `{e['source']}:{e['line']}`.","", "Callers: "+(", ".join(f"`{s['file']}:{s['line']}`" for s in e["callers"]) or "No direct screen call found; inspect delegation/legacy path."),"", "```cpp",e["signature"],*e["constants"],*e["drawing"],"```","", "Delegates: "+", ".join(e["delegates"]),"", "Fixed fixture inputs required: "+(", ".join(e["dynamic_tokens"]) or "Function arguments only."),""]
        for file,e in renderer_files.items():
            md += ["## "+file,"", "SHA256: `"+e["sha256"]+"`.","", "```cpp",*e["constants"],*e["drawing"],"```",""]
        (a.output/"mobus-source-coordinates.md").write_text("\n".join(md))
        print("Inventoried",len(entries),"facade entrypoints,",len(renderer_files),"renderer files and",len(result["screen_files"]),"screen source files")


if __name__=="__main__":main()
